@Tariff.Comparison.Api_HostAddress = http://localhost:5127

POST {{Tariff.Comparison.Api_HostAddress}}/products/
Accept: application/json
Content-Type: application/json

{
    "annualConsumption": 100
}

###
